version: '3.9'
services:
  server:
    container_name: servernew
    build: .
    ports:
      - '5000:5000'
  db:
    container_name: dbnew
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: